import { createElement } from "@lwc/engine-dom";
import SelfRegisterWithAccountModal from "c/selfRegisterWithAccountModal";

describe("c-self-register-with-account-modal", () => {
  afterEach(() => {
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    const element = createElement("c-self-register-with-account-modal", {
      is: SelfRegisterWithAccountModal
    });
    document.body.appendChild(element);

    expect(1).toBe(1);
  });
});
